export const PERMISSIONS = {
    // ADMISSION
    ADMISSION_CREATE: 'admission.create',
    ADMISSION_VIEW_SELF: 'admission.view_own',
    ADMISSION_VIEW_ALL: 'admission.view_all',
    ADMISSION_REVIEW: 'admission.review',
    ADMISSION_RECOMMEND: 'admission.recommend',
    ADMISSION_APPROVE: 'admission.approve',
    ADMISSION_REJECT: 'admission.reject',
    ADMISSION_ENROL: 'admission.enrol',

    // STUDENT
    STUDENT_CREATE: 'STUDENT_CREATE',
    STUDENT_VIEW: 'STUDENT_VIEW',
    STUDENT_VIEW_SELF: 'STUDENT_VIEW_SELF',
    STUDENT_UPDATE: 'STUDENT_UPDATE',
    STUDENT_ASSIGN_SECTION: 'STUDENT_ASSIGN_SECTION',

    // ACADEMIC
    ACADEMIC_SETUP: 'ACADEMIC_SETUP',
    ACADEMIC_VIEW: 'ACADEMIC_VIEW',
    ACADEMIC_ASSIGN_FACULTY: 'ACADEMIC_ASSIGN_FACULTY',
    CLASS_VIEW: 'CLASS_VIEW',
    CLASS_CREATE: 'CLASS_CREATE',
    SECTION_VIEW: 'SECTION_VIEW',
    SECTION_CREATE: 'SECTION_CREATE',

    // TRANSPORT
    TRANSPORT_SETUP: 'TRANSPORT_SETUP',
    TRANSPORT_VIEW: 'TRANSPORT_VIEW',
    TRANSPORT_VIEW_SELF: 'TRANSPORT_VIEW_SELF',
    TRANSPORT_ASSIGN: 'TRANSPORT_ASSIGN',

    // TRANSPORT OPS (Phase T3)
    TRIP_EXECUTE: 'TRIP_EXECUTE',
    TRIP_VIEW_SELF: 'TRIP_VIEW_SELF',
    TRIP_MONITOR: 'TRIP_MONITOR',

    // FEES
    FEES_VIEW: 'FEES_VIEW',
    FEES_SETUP: 'FEES_SETUP',
    FEES_ASSIGN: 'FEES_ASSIGN',
    PAYMENT_RECORD: 'PAYMENT_RECORD',
    DASHBOARD_VIEW_PARENT: 'DASHBOARD_VIEW_PARENT',

    // ATTENDANCE
    ATTENDANCE_MARK: 'ATTENDANCE_MARK',
    ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
    ATTENDANCE_VIEW_SELF: 'ATTENDANCE_VIEW_SELF',

    // DASHBOARD
    DASHBOARD_VIEW_ADMIN: 'DASHBOARD_VIEW_ADMIN',
    DASHBOARD_VIEW_FACULTY: 'DASHBOARD_VIEW_FACULTY',

    // EXAMS
    SUBJECT_VIEW: 'SUBJECT_VIEW',
    SUBJECT_CREATE: 'SUBJECT_CREATE',
    EXAM_VIEW: 'EXAM_VIEW',
    EXAM_CREATE: 'EXAM_CREATE',
    MARKS_VIEW: 'MARKS_VIEW',
    MARKS_ENTER: 'MARKS_ENTER',

    // TIMETABLE
    TIMETABLE_VIEW: 'TIMETABLE_VIEW',
    TIMETABLE_CREATE: 'TIMETABLE_CREATE',

    // FACULTY & STAFF MANAGEMENT
    FACULTY_PROFILE_MANAGE: 'FACULTY_PROFILE_MANAGE',
    STAFF_PROFILE_MANAGE: 'STAFF_PROFILE_MANAGE',
    SUBJECT_ASSIGN_FACULTY: 'SUBJECT_ASSIGN_FACULTY',
    SUBJECT_UPDATE_OWN: 'SUBJECT_UPDATE_OWN',
};

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
