export enum PermissionCode {
  ATTEMPT_WRITE = 'assessment.attempt.write',
  ATTEMPT_VIEW = 'assessment.attempt.view',
  QUESTION_VIEW = 'assessment.question.view',
  QUESTION_MANAGE = 'assessment.question.manage',
  QUESTION_CREATE = 'assessment.question.create',
  QUESTION_UPDATE = 'assessment.question.update',
  QUESTION_DELETE = 'assessment.question.delete',
  QUESTION_REVIEW = 'assessment.question.review',
  SCHEDULE_MANAGE = 'assessment.schedule.manage',
  SCHEDULE_VIEW = 'assessment.schedule.view',
  EVALUATION_MANAGE = 'assessment.evaluation.manage',
  RESULT_VIEW = 'assessment.result.view',
  RESULT_PUBLISH = 'assessment.result.publish',
  ANALYTICS_VIEW = 'assessment.analytics.view',
  SETTINGS_MANAGE = 'assessment.settings.manage',
  FOLDER_MANAGE = 'assessment.folder.manage',
  ASSET_UPLOAD = 'assessment.asset.upload',
}
