// utils/ConflictEngine.ts
// Simple rule engine for calendar conflict detection
import { Calendar, CalendarConflict } from '../types/Calendar';
import { isValidTransition } from './Lifecycle'; // Not used here but exported for completeness

export type ConflictRule = {
  code: string;
  severity: 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';
  description: string;
  check: (calendar: Calendar) => Promise<boolean>;
};

import { supabase } from '../../../shared/supabase';

// Placeholder implementations – real logic would query related tables via repository
const rules: ConflictRule[] = [
  {
    code: 'ROOM_OVERLAP',
    severity: 'ERROR',
    description: 'Two exams scheduled in the same room at overlapping times.',
    check: async (calendar) => {
      const { data, error } = await supabase
        .from('academic_calendar_events')
        .select('location, start_timestamp, end_timestamp')
        .eq('academic_calendar_id', calendar.id)
        .not('location', 'is', null);
      if (error || !data) return false;
      for (let i = 0; i < data.length; i++) {
        for (let j = i + 1; j < data.length; j++) {
          if (data[i].location === data[j].location) {
            const start1 = new Date(data[i].start_timestamp).getTime();
            const end1 = new Date(data[i].end_timestamp).getTime();
            const start2 = new Date(data[j].start_timestamp).getTime();
            const end2 = new Date(data[j].end_timestamp).getTime();
            if (start1 < end2 && start2 < end1) return true;
          }
        }
      }
      return false;
    },
  },
  {
    code: 'INVIGILATOR_OVERLAP',
    severity: 'ERROR',
    description: 'Invigilator assigned to overlapping exams.',
    check: async (calendar) => false,
  },
  {
    code: 'STUDENT_OVERLAP',
    severity: 'ERROR',
    description: 'Student scheduled for overlapping exams.',
    check: async (calendar) => {
      // Assume an RPC or external service call in a real app, mock it for now
      // Example: check if calendar has a flag indicating student overlaps
      return false;
    },
  },
  {
    code: 'EXAM_OUTSIDE_SEASON',
    severity: 'ERROR',
    description: 'Exam scheduled outside the approved exam season.',
    check: async (calendar) => {
       const { data, error } = await supabase
        .from('academic_calendar_events')
        .select('start_timestamp, end_timestamp')
        .eq('academic_calendar_id', calendar.id);
       if (error || !data) return false;
       
       // Using hypothetical calendar boundaries 
       const calStart = (calendar as any).start_date ? new Date((calendar as any).start_date).getTime() : 0;
       const calEnd = (calendar as any).end_date ? new Date((calendar as any).end_date).getTime() : Infinity;
       
       for (const event of data) {
         const evStart = new Date(event.start_timestamp).getTime();
         const evEnd = new Date(event.end_timestamp).getTime();
         if (evStart < calStart || evEnd > calEnd) return true;
       }
       return false;
    },
  },
  {
    code: 'HOLIDAY',
    severity: 'CRITICAL',
    description: 'Exam scheduled on a holiday or institution closure day.',
    check: async (calendar) => false,
  },
  {
    code: 'CAPACITY_EXCEEDED',
    severity: 'ERROR',
    description: 'Room capacity exceeded for scheduled exam.',
    check: async (calendar) => false,
  },
  {
    code: 'DUPLICATE_SUBJECT',
    severity: 'WARNING',
    description: 'Same subject scheduled multiple times in the same day.',
    check: async (calendar) => false,
  },
  // Configurable rules – placeholder defaults
  {
    code: 'BUFFER_TIME',
    severity: 'WARNING',
    description: 'Insufficient buffer time between consecutive exams.',
    check: async (calendar) => false,
  },
  {
    code: 'MAX_EXAMS_PER_ROOM',
    severity: 'INFO',
    description: 'Maximum exams per room per day limit reached.',
    check: async (calendar) => false,
  },
  {
    code: 'MAX_INVIGILATION_HOURS',
    severity: 'INFO',
    description: 'Invigilator exceeds daily invigilation hour limit.',
    check: async (calendar) => false,
  },
];

export default class ConflictEngine {
  static async detectConflicts(calendar: Calendar): Promise<CalendarConflict[]> {
    const conflicts: CalendarConflict[] = [];
    for (const rule of rules) {
      const violated = await rule.check(calendar);
      if (violated) {
        conflicts.push({
          id: '', // will be generated by DB when persisted
          calendar_id: calendar.id,
          rule_code: rule.code,
          severity: rule.severity,
          description: rule.description,
          resolved: false,
          resolved_by: null,
          resolved_at: null,
          resolution_notes: null,
        });
      }
    }
    return conflicts;
  }
}
